spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1999
    url: jdbc:mysql://localhost:3306/db_dianshang?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
  rabbitmq:
    addresses: 127.0.0.1
    port: 5672
    username: guest
    password: guest
#    rabbitMQ
mybatis:
  configuration:
    map-underscore-to-camel-case: true #下划线转驼峰
  mapper-locations: classpath:mappers/*.xml
logging:
  pattern:
    console: "[%thread] %-5level %logger{36} - %msg%n"
wx:
  appId: -
  mchId: -
  mchKey: -
  notifyUrl: -
  returnUrl: -
alipay:
  appId:-
  privateKey: -
  publicKey: -
  notifyUrl: -
  returnUrl: -

